name: Wirediff CI

on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]
  workflow_dispatch:

jobs:
  # build_ubuntu:
  # 
  #   runs-on: ubuntu-latest
  # 
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: install deps
  #     run: sudo apt-get install build-essential qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools tshark
  #   - name: qmake
  #     run: qmake
  #   - name: make
  #     run: make

  build_windows:

    runs-on: windows-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        py7zrversion: '>=0.20.2'
        version: "5.15.2"
        host: "windows"
        target: "desktop"
        arch: "win64_msvc2019_64"
    - name: Install Ilammy
      uses: ilammy/msvc-dev-cmd@v1
    - name: Create Makefile
      run: qmake
    - name: Compile App
      run: |
         ls
         nmake
    - name: Check if we got something
      run: |
         ls release
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: release/qtwirediff.exe
